# Maya import types
import_type:
  - 'mayaAscii'
  - 'mayaBinary'
  - 'Alembic'
  - 'FBX'
  - 'OBJ'
  - 'ASS' # Stand-Ins
  - 'USD import'

# Asset/Shot root path
asset_root: assets/{Asset_type}/{Asset_Name}/{Task}
seq_root: seq/{Sequence}/{Shot}/{Task}

# Asset/Shot work and publish area
asset_work_area:
  definition: '@asset_root/work'
shot_work_area:
  definition: '@seq_root/work'
asset_publish_area:
  definition: '@asset_root/publish'
shot_publish_area:
  definition: '@seq_root/publish'
